version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpressdata:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_ROOT_PWD: ${DB_ROOT_PWD}
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    volumes:
      - wordpressdata:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadbdata:
    driver: local
    driver_opts:
      type: none
      #      device: /home/rjeong/data/mysql
      device: /Users/raehyeon/data/mysql
      o: bind
  wordpressdata:
    driver: local
    driver_opts:
      type: none
      #      device: /home/rjeong/data/wordpress
      device: /Users/raehyeon/data/wordpress
      o: bind
